paths:
  output_dir:
  fastq_dir:
  reference:
  chain_file:
  chromosome_mapping:
  barcodes:
  ref_vcf:
  centromere:

parameters:
  chopper:
    quality:
    min_len:
  breadth_of_coverage:
    depth_cutoff:
  breadth_of_coverage_merged:
    depth_cutoff:
  deep_variant:
    BIN_VERSION:
  variant_filtering:
    min_QUAL:
    min_DP:


resources:
  nanoplot_raw:
    threads:
    memory:
  extract_headers:
    threads:
    memory:
  filter_reads:
    threads:
    memory:
  trim_reads:
    threads:
    memory:
  nanoplot_after_filtering:
    threads:
    memory:
  index_reference:
    threads:
    memory:
  alignment:
    threads:
    memory:
  qualimap:
    threads:
    memory:
  samtools_depth:
    threads:
    memory:
  calculate_mean_and_median_depth:
    threads: 1
    memory:
  breadth_of_coverage:
    threads: 1
    memory:
  count_bam:
    threads:
    memory:
  fold_80:
    threads: 1
    memory:
  merge_bams:
    threads:
    memory:
  qualimap_merged:
    threads:
    memory:
  samtools_depth_merged:
    threads:
    memory:
  calculate_mean_and_median_depth_merged:
    threads: 1
    memory:
  breadth_of_coverage_merged:
    threads: 1
    memory:
  count_bam_merged:
    threads:
    memory:
  fold_80_merged:
    threads: 1
    memory:
  deep_variant:
    threads:
    memory:
  variant_filtering:
    threads: 1
    memory:
  unique_SNPs:
    threads: 1
    memory:
  bed_maker:
    threads: 1
    memory:
  liftover:
    threads: 1
    memory:
  chromosome_name_conversion:
    threads: 1
    memory:
  filter_fingerprints:
    threads: 1
    memory:
  validation_fingerprints_alt:
    threads: 1
    memory:
  validation_fingerprints_ref:
    threads: 1
    memory:
  barcodes_positions_new_ref:
    threads: 1
    memory:
  chromosome_arms:
    threads: 1
    memory:
  report_html:
    threads: 1
    memory: 1000
